-- 038 — trainings.user_id ON DELETE CASCADE (GDPR Art. 17, teacher.py::delete_student).
--
-- NUMBERING: 037 is deliberately skipped. It is already claimed by the
-- fully-authored „Eigene Objekte" pair in docs/plans/eigene-objekte-sql/
-- (20260805120000_037_own_objects.sql + its rollback twin), which moves into
-- this directory when that feature lands. Two files numbered 037 would be
-- worse than a gap; `supabase db push` orders by the TIMESTAMP prefix, not by
-- the human NNN label, and 20260831 > 20260805, so the ordering is correct
-- either way.
--
-- WHAT WAS BROKEN. `public.trainings.user_id` was the ONLY foreign key to
-- `public.users` in the whole schema with no ON DELETE clause
-- (baseline.sql:62 — `UUID NOT NULL REFERENCES public.users(id)`; the twelve
-- others are CASCADE or SET NULL). Postgres therefore defaults it to NO
-- ACTION, so deleting an auth user cascaded auth.users → public.users
-- (baseline.sql:39) and then RAISED 23503 against this constraint.
--
-- Consequence, measured: a student who has ever started ONE training could
-- not be deleted at all. `DELETE /teacher/students/{id}` erased that
-- student's HuggingFace repos FIRST and only then hit the 500 — so a teacher
-- discharging a GDPR Art. 17 request destroyed the datasets, kept the
-- account, and was told only „Konto konnte nicht gelöscht werden". Retrying
-- could never succeed. The route ordering is fixed in the same change; this
-- migration removes the block itself.
--
-- TRADE-OFF, deliberate: CASCADE deletes the student's training history rows
-- along with the account. That history is personal data generated by the
-- student (dataset/model names carry their HF namespace), so Art. 17 requires
-- its erasure anyway — but it does mean the platform keeps no per-student
-- audit trail of past runs after a deletion. Credits accounting is not
-- affected: it lives on public.users, which is already cascaded.
--
-- Nothing references public.trainings, so this cascade is self-contained
-- (verified: no FK anywhere targets that table).

ALTER TABLE public.trainings
  DROP CONSTRAINT trainings_user_id_fkey;

ALTER TABLE public.trainings
  ADD CONSTRAINT trainings_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

COMMENT ON CONSTRAINT trainings_user_id_fkey ON public.trainings IS
    'ON DELETE CASCADE (038): a GDPR erasure of the student must not be blocked by their training history, which is itself personal data.';
