/*
 * Copyright 2026 EduBotics
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

// THE icon table: one semantic name per meaning, one Lucide component each
// (owner decision D7: Lucide everywhere, plus four custom Lucide-style icons in
// custom.js). This is the ONLY module that imports `react-icons/lu`, and no
// module in src/ may import any other react-icons set
// (components/icons/__tests__/noIconGlyphs.test.js fences both). Named imports
// only: `react-icons` is `sideEffects: false`, so the bundle carries exactly the
// icons listed here.
//
// A name says what the icon MEANS on screen, never what it looks like, so a
// later redesign changes one line here and no call site.

import {
  LuActivity,
  LuAlarmClock,
  LuArrowLeft,
  LuArrowRightLeft,
  LuArrowUp,
  LuBlocks,
  LuBookmark,
  LuBox,
  LuBug,
  LuCamera,
  LuChartLine,
  LuCheck,
  LuChevronDown,
  LuChevronRight,
  LuChevronsLeft,
  LuChevronsRight,
  LuCircle,
  LuCircleAlert,
  LuCircleCheck,
  LuCircleDot,
  LuCircleX,
  LuClapperboard,
  LuClipboardList,
  LuCloud,
  LuCloudUpload,
  LuCoffee,
  LuConstruction,
  LuCopy,
  LuCornerDownLeft,
  LuCpu,
  LuDatabase,
  LuDownload,
  LuEllipsis,
  LuExternalLink,
  LuFileDown,
  LuFileText,
  LuFileUp,
  LuFlame,
  LuFolder,
  LuFolderOpen,
  LuGamepad2,
  LuGitMerge,
  LuGraduationCap,
  LuHand,
  LuHistory,
  LuHourglass,
  LuHouse,
  LuInfo,
  LuKeyRound,
  LuLink,
  LuLoaderCircle,
  LuLock,
  LuLockOpen,
  LuLogOut,
  LuMapPin,
  LuMaximize2,
  LuMenu,
  LuMerge,
  LuMinus,
  LuNotebookPen,
  LuPalette,
  LuPause,
  LuPencil,
  LuPiggyBank,
  LuPlay,
  LuPlus,
  LuPuzzle,
  LuRedo2,
  LuRefreshCw,
  LuRotateCcw,
  LuSave,
  LuSearch,
  LuSend,
  LuSettings,
  LuSkipForward,
  LuSlidersHorizontal,
  LuSparkles,
  LuSquare,
  LuStar,
  LuStepForward,
  LuTarget,
  LuTerminal,
  LuTrash2,
  LuTriangleAlert,
  LuUndo2,
  LuUnlink,
  LuUnplug,
  LuUpload,
  LuUsers,
  LuVideo,
  LuVolume2,
  LuVolumeX,
  LuX,
  LuZap,
} from 'react-icons/lu';
import { IconGripper, IconLeaderArm, IconPython, IconRobotArm } from './custom';

export const ICONS = Object.freeze({
  // Vormachen: the three kinds (owner decision D10) and the arm controls.
  record: LuCircleDot,
  pose: LuMapPin,
  ziel: LuTarget,
  hand: LuHand,
  lock: LuLock,
  lockOpen: LuLockOpen,
  robotArm: IconRobotArm,
  leaderArm: IconLeaderArm,
  gripper: IconGripper,

  // Running, stepping, reviewing.
  play: LuPlay,
  pause: LuPause,
  step: LuStepForward,
  stop: LuSquare,
  skipForward: LuSkipForward,
  again: LuRotateCcw,
  check: LuCheck,
  checkCircle: LuCircleCheck,
  close: LuX,
  errorCircle: LuCircleX,
  alertCircle: LuCircleAlert,
  warning: LuTriangleAlert,
  info: LuInfo,
  dot: LuCircle,
  loading: LuLoaderCircle,
  hourglass: LuHourglass,
  debug: LuBug,
  search: LuSearch,

  // Editing.
  undo: LuUndo2,
  redo: LuRedo2,
  fit: LuMaximize2,
  save: LuSave,
  fileExport: LuFileUp,
  fileImport: LuFileDown,
  fileText: LuFileText,
  palette: LuPalette,
  pencil: LuPencil,
  plus: LuPlus,
  minus: LuMinus,
  trash: LuTrash2,
  copy: LuCopy,
  more: LuEllipsis,
  chevronDown: LuChevronDown,
  chevronRight: LuChevronRight,
  chevronsLeft: LuChevronsLeft,
  chevronsRight: LuChevronsRight,
  arrowLeft: LuArrowLeft,
  arrowUp: LuArrowUp,
  enterKey: LuCornerDownLeft,
  externalLink: LuExternalLink,
  refresh: LuRefreshCw,
  history: LuHistory,
  send: LuSend,
  sparkles: LuSparkles,
  sliders: LuSlidersHorizontal,
  menu: LuMenu,

  // Program notations (NewProgramDialog).
  blocks: LuPuzzle,
  python: IconPython,
  java: LuCoffee,

  // Places and things.
  camera: LuCamera,
  video: LuVideo,
  gamepad: LuGamepad2,
  box: LuBox,
  graduationCap: LuGraduationCap,
  folder: LuFolder,
  folderOpen: LuFolderOpen,
  home: LuHouse,
  bookmark: LuBookmark,
  star: LuStar,
  database: LuDatabase,
  cloud: LuCloud,
  cloudUpload: LuCloudUpload,
  download: LuDownload,
  upload: LuUpload,
  merge: LuGitMerge,
  mergeData: LuMerge,
  cpu: LuCpu,
  terminal: LuTerminal,
  settings: LuSettings,
  logout: LuLogOut,
  key: LuKeyRound,
  link: LuLink,
  unlink: LuUnlink,
  unplugged: LuUnplug,
  alarm: LuAlarmClock,
  flame: LuFlame,
  zap: LuZap,
  construction: LuConstruction,
  users: LuUsers,
  notebook: LuNotebookPen,
  piggyBank: LuPiggyBank,
  chart: LuChartLine,
  activity: LuActivity,
  moveAcross: LuArrowRightLeft,
  task: LuClipboardList,
  widgets: LuBlocks,
  volumeOn: LuVolume2,
  volumeOff: LuVolumeX,
  clapperboard: LuClapperboard,
});

export const ICON_NAMES = Object.freeze(Object.keys(ICONS));

/** True when `name` is a registered icon. */
export function isIconName(name) {
  return typeof name === 'string' && Object.prototype.hasOwnProperty.call(ICONS, name);
}
