; EduBotics Setup — Inno Setup Script
; Builds EduBotics_Setup.exe installer
;
; Ships a bundled WSL2 distro (assets\edubotics-rootfs.tar.gz) containing
; headless Docker Engine. Docker Desktop is uninstalled during setup if present.
;
; ─── Pinned third-party dependencies ──────────────────────────────────
; usbipd-win is downloaded + executed elevated during install. We pin
; the exact version + SHA256 here so install_prerequisites.ps1 can
; verify the MSI before msiexec runs — defends against MITM/mirror
; tampering and against an upstream `latest` shipping a breaking change.
;
; Asset naming: usbipd-win 5.x ships per-architecture MSIs named
;   usbipd-win_<VERSION>_x64.msi
; (the older 4.x suffix-less naming is gone, so the GitHub
; "latest/download/usbipd-win_x64.msi" alias also no longer resolves).
;
; Release procedure when bumping usbipd-win:
;   1. Update UsbipdVersion below.
;   2. PowerShell:
;        $url = "https://github.com/dorssel/usbipd-win/releases/download/v<NEW>/usbipd-win_<NEW>_x64.msi"
;        Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\u.msi" -UseBasicParsing
;        (Get-FileHash "$env:TEMP\u.msi" -Algorithm SHA256).Hash
;      Paste the 64-char hex output into UsbipdSha256.
;   3. Smoke-test the installer end-to-end on a clean Windows VM.
#define UsbipdVersion "5.3.0"
; SHA256 of usbipd-win_5.3.0_x64.msi (downloaded + verified 2026-04-25).
; Source: https://github.com/dorssel/usbipd-win/releases/tag/v5.3.0
; UsbipdSha256: leave as the literal "RELEASE_PIN_NEEDED" sentinel ONLY if
; you intentionally want the unsigned-download fallback for a dev build —
; install_prerequisites.ps1 hard-fails on that sentinel for production.
#define UsbipdSha256 "1C984914AEC944DE19B64EFF232421439629699F8138E3DDC29301175BC6D938"

[Setup]
AppId={{B7E3F2A1-8C4D-4E5F-9A6B-1D2E3F4A5B6C}
AppName=EduBotics
AppVersion=2.8.1
AppPublisher=EduBotics
DefaultDirName={autopf}\EduBotics
DefaultGroupName=EduBotics
OutputBaseFilename=EduBotics_Setup
OutputDir=output
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=admin
WizardStyle=modern
LicenseFile=assets\license.txt
SetupIconFile=assets\icon.ico
UninstallDisplayIcon={app}\gui\EduBotics.exe
; ChangesEnvironment=yes broadcasts WM_SETTINGCHANGE at the end of
; install so processes started AFTER Setup ends (via explorer.exe,
; Start menu shortcuts) pick up the updated system PATH — which the
; usbipd-win MSI extends with C:\Program Files\usbipd-win. Without
; this directive, students who don't reboot can still hit "usbipd
; not on PATH" if they launch EduBotics from any process that was
; running before install (incl. the postinstall checkbox). The GUI
; also self-heals via gui/app/usbipd_resolver.py — this directive is
; belt-and-suspenders for any path that shells out to `usbipd`
; without going through the resolver.
ChangesEnvironment=yes

[InstallDelete]
; Wipe the entire gui/ folder before upgrade — guarantees no stale files
; from older versions (renamed modules, removed DLLs, etc.) stick around.
; PyInstaller's full output goes here anyway, so nothing user-modified.
Type: filesandordirs; Name: "{app}\gui"
; Wipe scripts/ for same reason — we sometimes rename/remove .ps1 helpers.
Type: filesandordirs; Name: "{app}\scripts"
; Old v2.1.0 / v2.2.0 layout wrote .env into Program Files. v2.2.1+ moved
; it to %LOCALAPPDATA%\EduBotics\.env, so clean up the legacy file.
Type: files; Name: "{app}\docker\.env"
; Legacy cleanup: the retired offline bundle used to seed a digest sidecar
; here. The GUI no longer reads it, but wipe it on upgrade so a machine that
; once had an offline install carries no stale file forward.
Type: files; Name: "{app}\docker\bundled_digests.json"
; Old rootfs copies from previous versions — keep the ship folder tidy.
Type: filesandordirs; Name: "{app}\wsl_rootfs"

[Files]
; Docker compose files
Source: "..\docker\docker-compose.yml"; DestDir: "{app}\docker"; Flags: ignoreversion
Source: "..\docker\docker-compose.gpu.yml"; DestDir: "{app}\docker"; Flags: ignoreversion
Source: "..\docker\.env.template"; DestDir: "{app}\docker"; Flags: ignoreversion
; versions.env — pins IMAGE_TAG to the Docker images this .exe was built
; against, so pull_images.ps1 / verify_system.ps1 / gui/app/constants.py all
; reference the SAME bytes even months after the release ships (without this
; they fall back to :latest and drift past the .exe). Generated by
; release-installer.yml before iscc runs; skipped on local dev builds where
; the file doesn't exist (readers safely fall back to :latest).
Source: "..\docker\versions.env"; DestDir: "{app}\docker"; Flags: ignoreversion skipifsourcedoesntexist
; Rootfs version stamp — ShouldImportDistro (below) + import_edubotics_wsl.ps1
; compare it against the marker baked into the existing distro
; (/etc/edubotics-rootfs-version) and SKIP the destructive unregister+re-import
; when the rootfs is unchanged, preserving the student's Docker volumes.
Source: "..\wsl_rootfs\ROOTFS_VERSION"; DestDir: "{app}\wsl_rootfs"; Flags: ignoreversion
; s6-overlay marker to auto-start ROS2 services (mounted by docker-compose.yml)
Source: "..\docker\physical_ai_server\.s6-keep"; DestDir: "{app}\docker\physical_ai_server"; Flags: ignoreversion

; Bundled WSL2 rootfs — contains Ubuntu 22.04 + headless Docker Engine + nvidia-container-toolkit.
; Built by wsl_rootfs/build_rootfs.sh before running iscc.
Source: "assets\edubotics-rootfs.tar.gz"; DestDir: "{app}\wsl_rootfs"; Flags: ignoreversion
; SHA256 sidecar — import_edubotics_wsl.ps1 verifies the tarball against
; this hash before `wsl --import`, so a corrupted download / swapped tar
; fails fast with a clear error instead of wedging WSL2.
Source: "assets\edubotics-rootfs.tar.gz.sha256"; DestDir: "{app}\wsl_rootfs"; Flags: ignoreversion

; GUI application (PyInstaller output)
; The dist folder is created by: cd gui && pyinstaller build.spec
Source: "..\gui\dist\EduBotics\*"; DestDir: "{app}\gui"; Flags: ignoreversion recursesubdirs

; Installer scripts (kept for manual troubleshooting)
Source: "scripts\*"; DestDir: "{app}\scripts"; Flags: ignoreversion

; Brand icon — also copied into {app} so shortcuts keep a stable IconFilename
; independent of PyInstaller's dist layout.
Source: "assets\icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autodesktop}\EduBotics starten"; Filename: "{app}\gui\EduBotics.exe"; WorkingDir: "{app}"; IconFilename: "{app}\icon.ico"
Name: "{group}\EduBotics starten"; Filename: "{app}\gui\EduBotics.exe"; WorkingDir: "{app}"; IconFilename: "{app}\icon.ico"
Name: "{group}\Installation prüfen"; Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -File ""{app}\scripts\verify_system.ps1"""; WorkingDir: "{app}"

[Run]
; Post-install steps — run in order (hidden, students only see Inno Setup progress)

; Step 0: Alte Docker-Desktop-Installation entfernen (falls vorhanden)
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\migrate_from_docker_desktop.ps1"""; \
  StatusMsg: "Frühere Docker-Desktop-Installation wird entfernt..."; \
  Flags: runhidden waituntilterminated

; Step 1: Voraussetzungen installieren (WSL2, usbipd)
; Pin usbipd-win to the version + SHA256 declared at the top of this
; .iss. install_prerequisites.ps1 verifies the SHA before msiexec runs.
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\install_prerequisites.ps1"" -UsbipdMsiUrl ""https://github.com/dorssel/usbipd-win/releases/download/v{#UsbipdVersion}/usbipd-win_{#UsbipdVersion}_x64.msi"" -UsbipdMsiSha256 ""{#UsbipdSha256}"""; \
  StatusMsg: "Voraussetzungen werden installiert (WSL2, usbipd)..."; \
  Flags: runhidden waituntilterminated

; Step 2: .wslconfig konfigurieren
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\configure_wsl.ps1"""; \
  StatusMsg: "WSL2-Einstellungen werden konfiguriert..."; \
  Flags: runhidden waituntilterminated

; Step 3: usbipd-Richtlinie konfigurieren
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\configure_usbipd.ps1"""; \
  StatusMsg: "USB-Geräterichtlinie wird konfiguriert..."; \
  Flags: runhidden waituntilterminated

; Step 4: EduBotics WSL2-Distro importieren (skipped if reboot pending)
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\import_edubotics_wsl.ps1"""; \
  StatusMsg: "EduBotics-Umgebung wird eingerichtet (kann 1-3 Min. dauern)..."; \
  Flags: runhidden waituntilterminated; \
  Check: ShouldImportDistro

; Step 5: Docker-Images bereitstellen (skipped if reboot pending or distro missing)
; pull_images.ps1 pulls from the primary registry (GHCR) with a Docker Hub
; fallback; reads IMAGE_TAG/REGISTRY/REGISTRY_FALLBACK from docker\versions.env.
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\pull_images.ps1"""; \
  StatusMsg: "Docker-Images werden bereitgestellt (kann etwas dauern)..."; \
  Flags: runhidden waituntilterminated; \
  Description: "Docker-Images jetzt bereitstellen (empfohlen)"; \
  Check: ShouldPullImages

; Step 6: Installation überprüfen
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\verify_system.ps1"""; \
  StatusMsg: "Installation wird überprüft..."; \
  Flags: runhidden waituntilterminated postinstall; \
  Description: "Installation überprüfen"

; Step 7: App starten (optional, nach der Installation)
; Launch via explorer.exe so the GUI inherits the post-WM_SETTINGCHANGE
; environment (which includes %ProgramFiles%\usbipd-win on PATH after
; ChangesEnvironment=yes broadcasts). Inno Setup launches Filename:
; targets as direct children of itself, so a bare {app}\gui\EduBotics.exe
; would inherit Setup's STALE env captured at install start — see the
; PATH-propagation race documented in gui/app/usbipd_resolver.py.
;
; The GUI also self-heals via the resolver, so this is belt-and-
; suspenders — but it shaves the awkward "find usbipd in Program Files"
; latency off the very first launch.
Filename: "{win}\explorer.exe"; \
  Parameters: """{app}\gui\EduBotics.exe"""; \
  Description: "EduBotics jetzt starten"; \
  Flags: nowait postinstall skipifsilent

[UninstallRun]
; Container beim Deinstallieren stoppen (läuft jetzt in der WSL-Distro).
; Das Script ermittelt die korrekten Pfade selbst — keine hart-codierten Pfade.
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\scripts\uninstall_stop_containers.ps1"""; \
  Flags: runhidden; \
  RunOnceId: "StopContainers"

; EduBotics WSL2-Distro deregistrieren — NUR mit Zustimmung (Check:).
; `wsl --unregister` zerstört die VHDX und damit ALLE Docker-Volumes
; (ai_workspace, huggingface_cache, edubotics_calib). Bis 2026-06-07 lief
; das ohne Rückfrage — der Upgrade-Pfad bekam mit v2.6.1 die ROOTFS_VERSION-
; Schutzabfrage, die Deinstallation wischte weiter stumm. Der Dialog in
; ConfirmDistroWipe() fragt mit Default NEIN (Daten behalten), damit auch
; /SUPPRESSMSGBOXES niemals stumm löscht.
Filename: "wsl.exe"; \
  Parameters: "--unregister EduBotics"; \
  Flags: runhidden; \
  RunOnceId: "UnregisterDistro"; \
  Check: ConfirmDistroWipe

[UninstallDelete]
; Legacy cleanup: the retired offline bundle staged multi-GB tarballs here.
; A fresh GHCR install never creates this dir, but remove it on uninstall so a
; machine that once had an offline install (or an aborted one) leaves nothing
; behind.
Type: filesandordirs; Name: "{commonappdata}\EduBotics\bundle"
; Legacy digest sidecar (not a tracked [Files] entry, so Inno's uninstall
; wouldn't otherwise remove it).
Type: files; Name: "{app}\docker\bundled_digests.json"

[Code]
// Pascal Script: Check if the EduBotics WSL distro is registered
function IsDistroRegistered(): Boolean;
var
  ResultCode: Integer;
  TempFile: String;
  Raw: AnsiString;
  S: String;
begin
  Result := False;
  TempFile := ExpandConstant('{tmp}\wsl_list.txt');
  // `wsl --list --quiet` writes BOM-less UTF-16LE. Inno's Unicode
  // LoadStringsFromFile mis-decodes that as ANSI (a NUL between every byte), so a
  // direct `Line = 'EduBotics'` never matched and this returned False even when the
  // distro WAS registered — which silently skipped Step 5's image pull via
  // ShouldPullImages -> IsDistroRegistered (the pilot bug). Every other consumer of
  // this command in the repo strips the NULs (import_edubotics_wsl.ps1,
  // pull_images.ps1, verify_system.ps1, gui/app/docker_manager.py); do the same
  // here: load the raw bytes, drop the NULs (and CR), then whole-line match.
  // Validated live against a real registered distro (old=FALSE, new=TRUE).
  if not Exec(ExpandConstant('{cmd}'), '/c wsl --list --quiet > "' + TempFile + '" 2>&1', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    exit;
  if not LoadStringFromFile(TempFile, Raw) then
    exit;
  S := String(Raw);
  StringChangeEx(S, #0, '', True);   // drop the interleaved UTF-16 NUL high-bytes
  StringChangeEx(S, #13, '', True);  // drop CR; LF remains the line separator
  if Pos(#10 + 'EduBotics' + #10, #10 + S + #10) > 0 then
    Result := True;
end;

// Check if a reboot is required (flag written by install_prerequisites.ps1)
function IsRebootRequired(): Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\scripts\.reboot_required'));
end;

// Read the shipped rootfs version stamp ({app}\wsl_rootfs\ROOTFS_VERSION).
// Empty string when the file is missing (dev builds without the stamp).
function GetShippedRootfsVersion(): String;
var
  Lines: TArrayOfString;
begin
  Result := '';
  if LoadStringsFromFile(ExpandConstant('{app}\wsl_rootfs\ROOTFS_VERSION'), Lines) then
    if GetArrayLength(Lines) > 0 then
      Result := Trim(Lines[0]);
end;

// Read the version marker baked into the existing distro's rootfs
// (/etc/edubotics-rootfs-version, UTF-8 single line). Empty string when the
// distro can't be queried or predates the marker (installers <= 2.6.0).
function GetDistroRootfsVersion(): String;
var
  ResultCode: Integer;
  TempFile: String;
  Lines: TArrayOfString;
begin
  Result := '';
  TempFile := ExpandConstant('{tmp}\distro_rootfs_version.txt');
  if not Exec(ExpandConstant('{cmd}'), '/c wsl -d EduBotics -- cat /etc/edubotics-rootfs-version > "' + TempFile + '" 2>&1', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    exit;
  if ResultCode <> 0 then
    exit;
  if not LoadStringsFromFile(TempFile, Lines) then
    exit;
  if GetArrayLength(Lines) > 0 then
    Result := Trim(Lines[0]);
end;

// Import the distro when WSL2 is fully up (no pending reboot) AND either no
// distro exists yet (fresh install — nothing to lose) or the shipped rootfs
// differs from the one the existing distro was imported from. A re-import
// DESTROYS the distro's Docker volumes (recorded datasets, HF cache,
// Roboter-Studio calibration), so when one is actually needed the student
// must explicitly confirm. Silent installs with /SUPPRESSMSGBOXES take the
// default (Yes) — the pre-2026-06 behavior.
function ShouldImportDistro(): Boolean;
var
  Shipped, Existing: String;
begin
  if IsRebootRequired() then
  begin
    Result := False;
    exit;
  end;
  if not IsDistroRegistered() then
  begin
    Result := True;
    exit;
  end;
  Shipped := GetShippedRootfsVersion();
  Existing := GetDistroRootfsVersion();
  if (Shipped <> '') and (Existing <> '') and (Shipped = Existing) then
  begin
    Log('EduBotics rootfs unchanged (version ' + Shipped + ') - re-import skipped, Docker volumes preserved.');
    Result := False;
    exit;
  end;
  Result := MsgBox(
    'Die EduBotics-Umgebung muss neu aufgebaut werden (System-Update).'
    + #13#10 + #13#10
    + 'Dabei werden alle lokal gespeicherten Daten gelöscht:'
    + #13#10 + '  - aufgenommene Datensätze (falls nicht zu Hugging Face hochgeladen)'
    + #13#10 + '  - heruntergeladene Modelle'
    + #13#10 + '  - die Roboter-Studio-Kalibrierung'
    + #13#10 + #13#10
    + 'Jetzt fortfahren?',
    mbConfirmation, MB_YESNO) = IDYES;
  if not Result then
    Log('User declined the rootfs re-import - keeping the existing EduBotics distro.');
end;

// Uninstall consent for the destructive distro wipe. Mirrors the upgrade
// dialog in ShouldImportDistro, but with the OPPOSITE default: declining an
// upgrade re-import merely postpones it, declining the uninstall wipe is the
// safe choice forever — a kept distro costs disk space, a wiped one costs a
// student their only copy of every dataset. MB_DEFBUTTON2 makes "Nein" the
// default, so silent uninstalls (/SUPPRESSMSGBOXES takes the default button)
// PRESERVE the data. Cached: Inno may evaluate Check: more than once.
var
  DistroWipeAsked: Boolean;
  DistroWipeConfirmed: Boolean;

function ConfirmDistroWipe(): Boolean;
begin
  if DistroWipeAsked then
  begin
    Result := DistroWipeConfirmed;
    exit;
  end;
  DistroWipeAsked := True;
  DistroWipeConfirmed := MsgBox(
    'Sollen auch alle EduBotics-Daten gelöscht werden?'
    + #13#10 + #13#10
    + 'Dabei werden unwiderruflich entfernt:'
    + #13#10 + '  - aufgenommene Datensätze (falls nicht zu Hugging Face hochgeladen)'
    + #13#10 + '  - heruntergeladene Modelle'
    + #13#10 + '  - die Roboter-Studio-Kalibrierung'
    + #13#10 + #13#10
    + 'Tipp: Datensätze vorher in der EduBotics-App zu Hugging Face hochladen.'
    + #13#10 + #13#10
    + 'Bei "Nein" wird nur das Programm entfernt; die Daten bleiben erhalten'
    + #13#10 + 'und werden bei einer Neuinstallation wiederverwendet.',
    mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES;
  if DistroWipeConfirmed then
    Log('Uninstall: user confirmed the distro wipe - Docker volumes will be deleted.')
  else
    Log('Uninstall: distro wipe declined/defaulted - EduBotics distro + data preserved.');
  Result := DistroWipeConfirmed;
end;

// Pull images only when the distro is ready.
function ShouldPullImages(): Boolean;
begin
  Result := (not IsRebootRequired()) and IsDistroRegistered();
end;

// Tell Inno Setup a reboot is needed after install
function NeedRestart(): Boolean;
begin
  Result := IsRebootRequired();
end;

// Delete the installer file from %TEMP% / %LOCALAPPDATA%\Temp after Setup
// finishes so stale copies from auto-update downloads don't pile up.
procedure CleanupSourceInstaller();
var
  SrcExe: String;
  LowerSrc: String;
  LowerLocal: String;
begin
  SrcExe := ExpandConstant('{srcexe}');
  LowerSrc := LowerCase(SrcExe);
  LowerLocal := LowerCase(ExpandConstant('{localappdata}'));
  if (Pos(LowerLocal, LowerSrc) > 0)
     or (Pos('\temp\', LowerSrc) > 0)
     or (Pos('\tmp\', LowerSrc) > 0) then
  begin
    DeleteFile(SrcExe);
  end;
end;

// Convert a Windows path to its /mnt/<drive>/... WSL form for the distro.
function ToWslPath(WinPath: String): String;
var
  Normalized: String;
  Drive: String;
  Rest: String;
begin
  Result := WinPath;
  if WinPath = '' then
    exit;
  Normalized := WinPath;
  StringChangeEx(Normalized, '\', '/', True);
  if (Length(Normalized) >= 2) and (Normalized[2] = ':') then
  begin
    Drive := LowerCase(Copy(Normalized, 1, 1));
    Rest := Copy(Normalized, 3, Length(Normalized));
    while (Length(Rest) > 0) and (Rest[1] = '/') do
      Rest := Copy(Rest, 2, Length(Rest));
    Result := '/mnt/' + Drive + '/' + Rest;
  end
  else
    Result := Normalized;
end;

// Stop running containers in the EduBotics WSL distro before installing new
// files (upgrade safety), and cleanup the downloaded installer from %TEMP%.
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  DockerDirWsl: String;
begin
  if CurStep = ssInstall then
  begin
    if IsDistroRegistered() then
    begin
      DockerDirWsl := ToWslPath(ExpandConstant('{app}\docker'));
      Exec('wsl.exe', '-d EduBotics --cd "' + DockerDirWsl + '" -- docker compose down',
           '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    end;
  end;
  if CurStep = ssDone then
  begin
    CleanupSourceInstaller();
  end;
end;
