networks:
  ros_net:
    driver: bridge

services:
  open_manipulator:
    container_name: open_manipulator
    image: ${REGISTRY:-nettername}/open-manipulator:latest
    tty: true
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    networks:
      - ros_net
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-30}
      - FOLLOWER_PORT=${FOLLOWER_PORT}
      - LEADER_PORT=${LEADER_PORT}
      - CAMERA_DEVICE_1=${CAMERA_DEVICE_1:-}
      - CAMERA_NAME_1=${CAMERA_NAME_1:-camera1}
      - CAMERA_DEVICE_2=${CAMERA_DEVICE_2:-}
      - CAMERA_NAME_2=${CAMERA_NAME_2:-camera2}
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    privileged: true

  physical_ai_server:
    container_name: physical_ai_server
    image: ${REGISTRY:-nettername}/physical-ai-server:latest
    depends_on:
      - open_manipulator
    tty: true
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    networks:
      - ros_net
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-30}
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ai_workspace:/workspace
      - huggingface_cache:/root/.cache/huggingface
      - /var/run/robotis/agent_sockets/physical_ai_server:/var/run/agent
      - ./physical_ai_server/.s6-keep:/etc/s6-overlay/s6-rc.d/user/contents.d/physical_ai_server:ro
    privileged: true

  physical_ai_manager:
    container_name: physical_ai_manager
    image: ${REGISTRY:-nettername}/physical-ai-manager:latest
    depends_on:
      - physical_ai_server
    networks:
      - ros_net
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  ai_workspace:
  huggingface_cache:
