#!/usr/bin/env python3
# Copyright 2026 EduBotics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Export the OMX *follower* URDF + the STL meshes it references into the React
# SPA's public dir so the 3D digital twin (PR-7) can fetch them offline with NO
# CDN / network access (classroom requirement).
#
# Why this script and not a build step: classrooms run the bundled image offline
# and the SPA build must NOT depend on running this. So we commit the OUTPUT
# (public/omx-urdf/) and a maintainer re-runs this only when the upstream URDF
# or meshes change.
#
# What it does (deterministic copy + path rewrite, NO geometry math, NO ROS):
#   1. read the pre-expanded follower URDF
#      open_manipulator/.../urdf/omx_f/omx_f.urdf
#      (already autogenerated from omx_f.urdf.xacro; correct axes + origins),
#   2. copy every referenced  package://open_manipulator_description/meshes/<sub>/<f>.stl
#      mesh into  public/omx-urdf/meshes/<f>.stl  (STL only; no textures),
#   3. rewrite the package:// URIs to relative  meshes/<f>.stl  paths that the
#      browser fetches from  /omx-urdf/meshes/<f>.stl ,
#   4. drop <collision> blocks (the twin only needs <visual>; halves the parse
#      work and the urdf-loader never builds collision geometry anyway).
#
# Run from the repo root:  python3 tools/export_omx_urdf_for_web.py

from __future__ import annotations

import re
import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

SRC_URDF = (
    REPO_ROOT
    / "open_manipulator"
    / "open_manipulator_description"
    / "urdf"
    / "omx_f"
    / "omx_f.urdf"
)
MESH_ROOT = (
    REPO_ROOT / "open_manipulator" / "open_manipulator_description" / "meshes"
)
OUT_DIR = (
    REPO_ROOT
    / "physical_ai_tools"
    / "physical_ai_manager"
    / "public"
    / "omx-urdf"
)

# package://open_manipulator_description/meshes/<subdir>/<file>.stl
PKG_MESH_RE = re.compile(
    r"package://open_manipulator_description/meshes/(?P<sub>[^/]+)/(?P<file>[^\"']+)"
)


def main() -> int:
    if not SRC_URDF.is_file():
        print(f"ERROR: source URDF not found: {SRC_URDF}", file=sys.stderr)
        return 1

    tree = ET.parse(SRC_URDF)
    root = tree.getroot()

    # 1. Drop <collision> blocks — the twin renders <visual> only.
    for link in root.findall("link"):
        for coll in link.findall("collision"):
            link.remove(coll)

    # 2./3. Find + copy every referenced mesh; rewrite its filename to relative.
    out_mesh_dir = OUT_DIR / "meshes"
    out_mesh_dir.mkdir(parents=True, exist_ok=True)

    copied: set[str] = set()
    referenced = 0
    for mesh in root.iter("mesh"):
        fn = mesh.get("filename", "")
        m = PKG_MESH_RE.match(fn)
        if not m:
            # Leave any non-package mesh URI untouched but warn — the omx_f
            # follower URDF is 100% package:// meshes, so this should never fire.
            if fn:
                print(f"WARN: non-package mesh URI left as-is: {fn}", file=sys.stderr)
            continue
        referenced += 1
        sub, fname = m.group("sub"), m.group("file")
        src_mesh = MESH_ROOT / sub / fname
        if not src_mesh.is_file():
            print(f"ERROR: referenced mesh missing: {src_mesh}", file=sys.stderr)
            return 1
        dst_mesh = out_mesh_dir / fname
        if fname not in copied:
            shutil.copy2(src_mesh, dst_mesh)
            copied.add(fname)
        # Browser fetches /omx-urdf/meshes/<fname>; urdf-loader resolves mesh
        # filenames relative to the .urdf location, so a bare relative path works.
        mesh.set("filename", f"meshes/{fname}")

    # 4. Write the rewritten URDF.
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_urdf = OUT_DIR / "omx_f.urdf"
    tree.write(out_urdf, encoding="unicode", xml_declaration=True)
    # ET writes a single-line declaration without a trailing newline; add one.
    text = out_urdf.read_text(encoding="utf-8")
    if not text.endswith("\n"):
        out_urdf.write_text(text + "\n", encoding="utf-8")

    total_kb = sum((out_mesh_dir / f).stat().st_size for f in copied) / 1024.0
    print(f"Wrote {out_urdf.relative_to(REPO_ROOT)}")
    print(f"Copied {len(copied)} STL mesh(es) ({referenced} mesh refs) -> "
          f"{out_mesh_dir.relative_to(REPO_ROOT)}")
    print(f"Total mesh size: {total_kb:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
