// Copyright 2026 EduBotics
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// EVERY German string of the Daten tab (spec §J.6, §G9). The owner-approved
// mockup's words verbatim, with the six approved corrections (N4) and the
// additions §J.6 lists. Nothing in components/Daten/ writes a sentence of its
// own.
//
// A string with values is ONE literal with `{name}` placeholders, filled by
// model/format.js::fill (or <Fill> where a value is markup) — never a template
// literal with `×`/`·` between two expressions, whose quasi a lone-glyph check
// would read as an icon (G-17). Quotes are typographic („…“), never straight.
// Counts go through model/format.js::plural with the `…One`/`…Many` pairs.

function deepFreeze(o) {
  Object.values(o).forEach((v) => {
    if (v && typeof v === 'object' && !Object.isFrozen(v)) deepFreeze(v);
  });
  return Object.freeze(o);
}

const DATEN_COPY = deepFreeze({
  count: {
    datasetOne: '{n} Datensatz',
    datasetMany: '{n} Datensätze',
    episodeOne: '{n} Episode',
    episodeMany: '{n} Episoden',
    listAnd: '{a} und {b}',
  },

  page: {
    eyebrow: 'Daten',
    title: 'Deine Datensätze',
    sub: '{datasets} von dir und deiner Gruppe · {changed} hier geändert, {local} nur hier gespeichert',
    fetch: 'Von Hugging Face holen',
    merge: 'Zusammenführen',
    filterLabel: 'Wessen Datensätze',
    filterAll: 'Alle',
    filterMine: 'Meine',
    filterGroup: 'Gruppe',
    search: 'Datensatz suchen',
    refreshLoading: 'Online-Liste wird geladen …',
    refreshJust: 'Online-Liste gerade geladen',
    refreshAgo: 'Online-Liste vor {n} Min. geladen',
    refresh: 'Aktualisieren',
    noResults: 'Keine Datensätze gefunden.',
    noResultsFor: 'Keine Datensätze gefunden für „{q}“.',
  },

  lib: {
    empty: 'Hier gibt es noch keine Datensätze. Nimm im Tab Aufnahme welche auf oder hole einen von Hugging Face.',
    offline: 'Keine Verbindung zum Roboter. Die Datensätze erscheinen, sobald er wieder verbunden ist.',
    noIdentity: 'Ohne Anmeldung kann EduBotics deine Datensätze nicht zuordnen. Melde dich an, um sie zu sehen.',
    noHfAccount: 'Für dein Konto ist noch kein Hugging-Face-Konto eingetragen. Trage auf der Startseite deinen Hugging-Face-Token ein, dann erscheinen hier deine Datensätze.',
    tokenNotActive: 'Dein Hugging-Face-Token ist auf dem Roboter nicht aktiv. Online-Datensätze, Hochladen und Holen gehen erst wieder, wenn es auf der Startseite aktiv ist.',
    hubFailed: 'Die Online-Liste konnte nicht geladen werden. Du siehst nur die Datensätze auf diesem Roboter.',
    hiddenCount: '{n} weitere Datensätze auf Hugging Face haben ein älteres Format oder stammen von einem anderen Roboter und werden hier nicht gezeigt.',
    hintsPending: 'Hinweise werden berechnet …',
    diskFree: '{gb} frei',
    diskFreeTitle: 'Freier Speicher auf dem Roboter',
    loading: 'Datensätze werden geladen …',
  },

  cloudOnly: 'Im Cloud-Modus gibt es keinen Roboter mit Datensätzen.',

  old: {
    image: 'Der Roboter läuft mit einer älteren Version von EduBotics. Für die neue Daten-Ansicht muss er aktualisiert werden.',
    sidecar: 'Die Daten-Ansicht des Roboters antwortet gerade nicht. EduBotics versucht es weiter …',
  },

  http: {
    generic: 'Die Daten konnten nicht geladen werden. Versuche es gleich noch einmal.',
  },

  sync: {
    localLabel: 'Nur hier',
    localTip: 'Nur auf diesem Roboter gespeichert.',
    onlineLabel: 'Nur online',
    onlineTip: 'Auf Hugging Face, noch nicht auf diesem Roboter.',
    currentLabel: 'Aktuell',
    currentTip: 'Hier und auf Hugging Face gleich.',
    changedLabel: 'Hier geändert – nicht hochgeladen',
    changedTip: 'Das Training nutzt noch die alte Version auf Hugging Face.',
    newerLabel: 'Online neuer',
    newerTip: 'Auf Hugging Face gibt es eine neuere Version.',
    conflictLabel: 'Hier und online verschieden',
    conflictTip: 'Hier und auf Hugging Face gibt es verschiedene Versionen. Entscheide, welche du behalten willst.',
    unknownLabel: 'Online-Stand unbekannt',
    unknownTip: {
      not_asked: 'Ob es auf Hugging Face eine andere Version gibt, wurde noch nicht geprüft.',
      unreachable: 'Hugging Face war gerade nicht erreichbar. Prüfe es mit „Aktualisieren“ noch einmal.',
      not_visible: 'Ob dieser Datensatz auf Hugging Face liegt, kann nur {name} sehen.',
    },
    refresh: 'Aktualisieren',
    recordLabel: 'Wird gerade aufgenommen',
    recordTip: 'Bearbeiten erst nach der Aufnahme.',
    uploadLabel: 'Wird hochgeladen',
    downloadLabel: 'Wird geladen',
    editLabel: 'Wird bearbeitet',
    keepBothLabel: 'Wird zusammengeführt',
    refreshingLabel: 'Wird aktualisiert …',
  },

  card: {
    episodes: 'Episoden',
    duration: 'Dauer',
    size: 'Größe',
    fps: 'Bilder/s',
    hintsCount: '{n} von {m} Episoden mit Hinweisen',
    hintsNone: 'Keine Auffälligkeiten',
    hintsAfterLoad: 'Hinweise nach dem Laden',
    previewAfterLoad: 'Vorschau nach dem Laden',
    statsLoading: 'Angaben werden von Hugging Face geladen …',
    copyOf: 'Kopie von {repo}',
    view: 'Ansehen',
    viewAfterRecording: 'Erst nach der Aufnahme',
    editAfterRecording: 'Bearbeiten erst nach der Aufnahme',
    loadAndView: 'Laden und ansehen',
    uploadNow: 'Jetzt hochladen',
    upload: 'Hochladen',
    pullNewer: 'Neuere Version laden',
    keepBoth: 'Beide behalten',
    loadOnline: 'Online-Version laden',
    uploadHere: 'Hier-Version hochladen',
    more: 'Weitere Aktionen',
    uploading: 'Wird hochgeladen …',
    downloading: 'Wird geladen … {done} von {total}',
    downloadingStart: 'Wird von Hugging Face geladen …',
    editing: 'Wird bearbeitet …',
    keepingBoth: 'Wird zusammengeführt …',
    percent: '{pct} %',
    cancel: 'Abbrechen',
    mergePick: 'Zum Zusammenführen auswählen',
    mergePickBlocked: 'Erst laden',
    refreshing: 'Wird aktualisiert …',
    crashed: 'Die Aufnahme wurde unterbrochen und nicht sauber beendet. Ansehen, Bearbeiten und Hochladen gehen nicht.',
    deleteWhole: 'Ganzen Datensatz löschen',
    incomplete: 'Unvollständig – die Aufnahme wurde unterbrochen.',
    old_format: 'Altes Format (v2.1) – kann hier nicht angesehen werden.',
    unsupported: 'Unbekanntes Format – kann hier nicht angesehen werden.',
    partnerOnly: 'Nur {name} kann diesen Datensatz hochladen.',
    partnerNote: 'Nur {name} kann diesen Datensatz hochladen: Er gehört zum Hugging-Face-Konto von {name}.',
  },

  menu: {
    toTraining: 'Weiter zum Training',
    trainChanged: 'Zuerst hochladen – das Training nutzt die Version auf Hugging Face.',
    trainLocal: 'Zuerst hochladen.',
    mergePick: 'Zum Zusammenführen auswählen',
    mergeNeedsLoad: 'Erst laden.',
    deleteWhole: 'Ganzen Datensatz löschen',
    deleteOnlineOnly: 'Liegt nur online – hier ist nichts zu löschen.',
    deleteFrees: 'Gibt {size} auf dem Roboter frei.',
    hubLink: 'Auf Hugging Face ansehen',
    hubLinkTitlePublic: 'Öffnet den Datensatz im LeRobot-Viewer von Hugging Face (neuer Tab).',
    hubLinkTitlePrivate: 'Öffnet die Seite des Datensatzes auf Hugging Face (neuer Tab). Einen privaten Datensatz siehst du dort nur, wenn du bei Hugging Face angemeldet bist.',
  },

  merge: {
    title: 'Zusammenführen',
    selected: '· {n} ausgewählt',
    pickHint: 'Wähle auf den Karten mindestens zwei Datensätze aus.',
    chip: '{name} · {n}',
    chipPartner: '{name} ({owner}) · {n}',
    unchanged: 'Die ausgewählten Datensätze bleiben unverändert. Es entsteht ein neuer Datensatz, nur hier, bis du ihn hochlädst.',
    nameLabel: 'Name des neuen Datensatzes',
    defaultName: '{name} gesamt',
    savedAs: 'wird gespeichert als {id}',
    go: 'Zusammenführen',
    goCount: '{n} Episoden zusammenführen',
    cancel: 'Abbrechen',
    check: {
      minTwo: 'Mindestens zwei Datensätze auswählen',
      versionBad: 'Unterschiedliches Datensatz-Format – lässt sich nicht zusammenführen',
      robotOk: 'Gleicher Roboter: {robot}',
      robotBad: 'Unterschiedliche Roboter – lässt sich nicht zusammenführen',
      fpsOk: 'Gleiche Bildrate: {fps} Bilder/s',
      fpsBad: 'Unterschiedliche Bildrate ({list} Bilder/s) – lässt sich nicht zusammenführen',
      camerasOk: 'Gleiche Kameras: {names}',
      camerasBad: 'Unterschiedliche Kameras – lässt sich nicht zusammenführen',
      jointsOk: 'Gleiche Gelenke ({n} Gelenke + Greifer)',
      jointsOkNoGripper: 'Gleiche Gelenke ({n} Gelenke)',
      jointsBad: 'Unterschiedliche Gelenke – lässt sich nicht zusammenführen',
      videoOk: 'Gleiches Videoformat: {codec} · {w} × {h}',
      videoBad: 'Unterschiedliches Videoformat – lässt sich nicht zusammenführen',
      statsOk: 'Gleiche Statistiken',
      statsBad: 'Unterschiedliche Statistiken – lässt sich nicht zusammenführen',
    },
  },

  player: {
    back: 'Alle Datensätze',
    eyebrow: 'Episoden ansehen',
    groupOwner: '{name} · Gruppe',
    loading: 'Episoden werden geladen …',
    loadFailed: 'Diese Episode konnte nicht geladen werden.',
    retry: 'Erneut versuchen',
    unplayable: 'Diese Episode kann hier nicht abgespielt werden: Ihr Video ist nicht an der Episodengrenze geschnitten.',
    episodes: 'Episoden',
    duration: 'Dauer',
    durationMin: '{t} min',
    fps: 'Bilder/s',
    size: 'Größe',
    cameras: 'Kameras',
    changedAt: 'Geändert',
    task: '„{task}“',
    withHints: '{n} mit Hinweisen',
    onlyHints: 'Nur mit Hinweisen',
    showAll: 'Alle zeigen',
    episodesLabel: 'Episoden',
    episode: 'Episode {n}',
    markEpisode: 'Episode {n} zum Löschen markieren',
    noHints: 'Keine Auffälligkeiten',
    marked: '{n} markiert',
    clearMarks: 'Aufheben',
    deleteMarked: 'Löschen …',
    markHint: 'Markiere schlechte Episoden mit dem Kästchen oder {key}.',
    keyDelete: 'Entf',
    viewLabel: 'Ansicht',
    viewCams: 'Kameras',
    view3d: '3D',
    viewBoth: 'Beides',
    legendFollower: 'Follower-Arm (gemessen)',
    legendLeader: 'Leader-Arm (Befehl)',
    tile3d: '3D',
    presetPersp: 'Perspektive',
    presetFront: 'Vorne',
    presetSide: 'Seite',
    presetTop: 'Oben',
    drag3d: 'Ziehen zum Drehen',
    offline3d: 'Das 3D-Modell erscheint, sobald der Roboter verbunden ist.',
    prevEpisode: 'Vorherige Episode',
    prevEpisodeTitle: 'Vorherige Episode (↑)',
    stepBack: 'Ein Bild zurück',
    stepBackTitle: 'Ein Bild zurück (←)',
    play: 'Abspielen',
    playTitle: 'Abspielen (Leertaste)',
    pause: 'Pause',
    pauseTitle: 'Pause (Leertaste)',
    stepForward: 'Ein Bild vor',
    stepForwardTitle: 'Ein Bild vor (→)',
    nextEpisode: 'Nächste Episode',
    nextEpisodeTitle: 'Nächste Episode (↓)',
    frame: 'Bild {i} / {n}',
    speedLabel: 'Tempo',
    speeds: ['0,25×', '0,5×', '1×', '2×'],
    mark: 'Markieren',
    markedOne: 'Markiert',
    markTitle: 'Episode zum Löschen markieren (Entf)',
    timeline: 'Zeitleiste',
    timelineValue: '{cur} von {total}',
    hintsTitle: 'Auffälligkeiten in Episode {n}',
    hintsNone: 'Keine Auffälligkeiten. Diese Episode sieht gut aus.',
    hintsPending: 'Hinweise werden berechnet …',
    toPlace: 'Zur Stelle',
    detailsTitle: 'Episode {n} · Details',
    chartsTitle: 'Gelenke',
    chartsNote: 'in Grad · Klick springt dorthin',
    chartAria: '{name}: Verlauf von Follower und Leader',
    keySpace: 'Leertaste',
    keySpaceDo: 'Abspielen/Pause',
    keyArrowsDo: 'ein Bild',
    keyShift: 'Umschalt',
    keyShiftDo: '5 Sekunden',
    keyUpDownDo: 'Episode',
    keyDeleteDo: 'markieren',
    keyLeft: '←',
    keyRight: '→',
    keyUp: '↑',
    keyDown: '↓',
  },

  details: {
    duration: 'Dauer',
    durationValue: '{t} s · {n} Bilder',
    cameras: 'Kameras',
    cameraFrames: '{camera} {n} Bilder',
    size: 'Größe',
    sizeValue: '≈ {size}',
    robot: 'Roboter',
    robotValue: '{name} ({id})',
    joints: 'Gelenke',
    jointsValue: '{state} gemessen (Follower) · {action} Befehle (Leader)',
    video: 'Video',
    videoValue: '{codec} · {w} × {h} · {fps} Bilder/s',
    task: 'Aufgabe',
    taskValue: '„{task}“',
    index: 'In den Daten: episode_index {i}',
  },

  tools: {
    label: 'Werkzeuge',
    deleteEpisodes: 'Episoden löschen',
    split: 'Aufteilen',
    merge: 'Zusammenführen',
    uploadNow: 'Jetzt hochladen',
    upload: 'Hochladen',
    alreadyCurrent: 'Ist schon aktuell auf Hugging Face.',
    toTraining: 'Weiter zum Training',
    trainChanged: 'Zuerst hochladen – das Training nutzt die Version auf Hugging Face.',
    deleteWhole: 'Ganzen Datensatz löschen',
  },

  banner: {
    newer: 'Auf Hugging Face gibt es eine neuere Version ({n} Episoden, {date}). Lade sie, bevor du hier etwas löschst – sonst überschreibst du sie beim nächsten Hochladen.',
    newerShort: 'Auf Hugging Face gibt es eine neuere Version. Lade sie, bevor du hier etwas löschst – sonst überschreibst du sie beim nächsten Hochladen.',
    newerButton: 'Neuere Version laden',
    changed: 'Hier geändert, aber noch nicht hochgeladen. Das Training nutzt noch die alte Version ({n} Episoden).',
    changedShort: 'Hier geändert, aber noch nicht hochgeladen. Das Training nutzt noch die alte Version.',
    changedButton: 'Jetzt hochladen',
    conflict: 'Hier und auf Hugging Face gibt es verschiedene Versionen. Behalte beide, oder entscheide dich für eine – die andere geht dabei verloren.',
  },

  keepBoth: {
    button: 'Beide behalten',
    // V1-5: the truth of G-2, in the core sentence the robot's texts share
    // (record_texts_de.HUB_CHANGED_SINCE_CHECK_DE)
    tip: '„Beide behalten“ behält alle neuen Episoden von hier und von Hugging Face. Was seit dem letzten Abgleich auf einer Seite gelöscht oder ersetzt wurde, bleibt weg. Gleiche Episoden kommen nur einmal vor. Danach wird der Datensatz hochgeladen.',
    progressTitle: 'Beide Versionen werden zusammengeführt …',
    stepDownload: 'Online-Version laden',
    stepMerge: 'Zusammenführen',
    stepUpload: 'Hochladen',
    done: 'Beide Versionen sind zusammengeführt und hochgeladen ({n} Episoden).',
    // the re-read after the job did not land: no count rather than „–"
    doneNoCount: 'Beide Versionen sind zusammengeführt und hochgeladen.',
  },

  conflict: {
    loadOnline: 'Online-Version laden',
    uploadHere: 'Hier-Version hochladen',
    losesHere: 'Deine Änderungen von hier gehen dabei verloren.',
    losesOnline: 'Episoden, die es nur auf Hugging Face gibt, gehen dabei verloren.',
  },

  tool: {
    deleteTitle: 'Episoden löschen',
    deleteSub: 'aus „{name}“ · {count}',
    deleteLabel: 'Welche Episoden?',
    placeholder: 'z. B. 3, 5, 10-15',
    splitTitle: 'Datensatz aufteilen',
    splitSub: 'Die gewählten Episoden kommen in einen neuen Datensatz. Der Rest bleibt in „{name}“. Bild und Daten bleiben unverändert.',
    splitLabel: 'Welche Episoden kommen in den neuen Datensatz?',
    splitNameLabel: 'Name des neuen Datensatzes',
    splitDefaultName: '{name} Teil 2',
    pickMarked: 'Markierte ({n})',
    pickHints: 'Alle mit Hinweisen ({n})',
    pickFifth: 'Jede 5. Episode',
    pickClear: 'Leeren',
    errNotNumber: '„{token}“ ist keine Episodennummer.',
    errRange: '{token}: Es gibt nur Episode 1 bis {max}.',
    errAll: 'Das wären alle Episoden. Lösche dafür den ganzen Datensatz.',
    errSplitAll: 'Mindestens eine Episode muss im alten Datensatz bleiben.',
    errNoName: 'Gib dem neuen Datensatz einen Namen.',
    errNameExists: 'Einen Datensatz mit diesem Namen gibt es hier schon.',
    previewDelete: '{part} Episoden werden gelöscht, {rest} bleiben und heißen danach Episode 1 bis {rest}.',
    previewPart: '{k} von {max}',
    chipEpisode: 'Episode {n}',
    chipMore: '… und {n} weitere',
    partnerOwns: 'Der Datensatz gehört {name} aus deiner Gruppe.',
    onlineStays: 'Auf Hugging Face bleibt die alte Version, bis du hochlädst.',
    irreversible: 'Das lässt sich nicht rückgängig machen.',
    cancel: 'Abbrechen',
    deleteButton: 'Löschen',
    deleteCountButton: '{count} löschen',
    splitButton: 'Aufteilen',
    splitKeeps: 'Bleibt',
    splitNew: 'Neu',
    splitEpisodes: '{count}',
    splitEpisodesList: '{count}: {list}',
    splitOnlyHere: 'Der neue Datensatz liegt nur hier, bis du ihn hochlädst.',
    splitChangesOriginal: '„{name}“ ist danach hier geändert.',
    splitNamePreview: 'wird gespeichert als {id}',
  },

  progress: {
    wait: 'Bitte warte kurz. Der Roboter bleibt währenddessen nutzbar.',
    deleteTitle: 'Episoden werden gelöscht …',
    deleteSteps: ['Daten neu schreiben', 'Videos schneiden – ohne Qualitätsverlust', 'Ergebnis prüfen'],
    mergeTitle: 'Datensätze werden zusammengeführt …',
    mergeSub: '{datasets}, {episodes}.',
    mergeSteps: ['Daten zusammenfügen', 'Videos kopieren – ohne Qualitätsverlust', 'Ergebnis prüfen'],
    splitTitle: 'Datensatz wird aufgeteilt …',
    splitSteps: ['Daten aufteilen', 'Videos kopieren – ohne Qualitätsverlust', 'Beide Teile prüfen'],
    deleteDatasetTitle: 'Datensatz wird gelöscht …',
  },

  confirm: {
    deleteMarkedTitle: '{count} löschen?',
    deleteMarkedBody: 'Sie werden aus „{name}“ auf diesem Roboter entfernt. {rest} Episoden bleiben und werden neu nummeriert (1 bis {rest}). Bild und Daten der übrigen Episoden bleiben unverändert.',
    deleteMarkedButton: '{count} löschen',
    deleteDatasetTitle: 'Ganzen Datensatz löschen?',
    deleteOnlineKeeps: '„{name}“ wird nur auf diesem Roboter gelöscht. Auf Hugging Face bleibt er erhalten ({n} Episoden, {date}).',
    deleteOnlineKeepsShort: '„{name}“ wird nur auf diesem Roboter gelöscht. Auf Hugging Face bleibt er erhalten.',
    deleteOnlyHere: '„{name}“ ist {only} gespeichert. Nach dem Löschen ist er endgültig weg.',
    deleteOnlyHerePartner: '„{name}“ von {owner} ist {only} gespeichert. Nach dem Löschen ist er endgültig weg.',
    onlyHere: 'nur hier',
    ack: 'Ich habe verstanden, dass es keine Kopie gibt.',
    frees: 'Gibt {size} auf dem Roboter frei.',
    deleteDatasetButton: 'Datensatz löschen',
  },

  del: {
    lostChanges: '{bold} – sie sind noch nicht hochgeladen.',
    lostChangesBold: 'Deine Änderungen von hier gehen verloren',
  },

  upload: {
    compareTitle: 'Auf Hugging Face gibt es diesen Datensatz schon',
    onHub: 'Auf Hugging Face',
    here: 'Hier',
    onHubMeta: '{dur} min · {date}',
    hereMeta: '{dur} min · geändert {date}',
    replaces: 'Beim Ersetzen wird die Version auf Hugging Face durch deine Version von hier überschrieben. Das Training nutzt danach die neue Version.',
    attention: 'Achtung:',
    newerLoses: 'Die Version auf Hugging Face ist neuer. Episoden, die es nur dort gibt, gehen verloren.',
    replaceButton: 'Ersetzen und hochladen',
    newTitle: '„{name}“ hochladen?',
    newButton: 'Hochladen',
    visibilityPublic: 'Wird öffentlich auf Hugging Face angelegt – jeder kann ihn sehen.',
    visibilityPrivate: 'Wird privat auf Hugging Face angelegt – nur dein Konto kann ihn sehen.',
    checking: 'Hugging Face wird gefragt …',
  },

  pull: {
    title: 'Neuere Version laden?',
    // „Online-Version laden" of a conflict or a crashed card: the hub copy is
    // not newer, only different (V2-15)
    titleOnline: 'Online-Version laden?',
    here: 'Hier',
    onHub: 'Auf Hugging Face',
    replaces: 'Die Version hier wird durch die neuere von Hugging Face ersetzt.',
    replacesOnline: 'Die Version hier wird durch die Version von Hugging Face ersetzt.',
    button: 'Laden',
  },

  newer: {
    title: 'Erst die neuere Version laden?',
    body: 'Auf Hugging Face liegt eine neuere Version von „{name}“: {bold} ({date}). Hier sind es {m}.',
    bodyShort: 'Auf Hugging Face liegt eine neuere Version von „{name}“.',
    loses: 'Wenn du hier löschst und dann hochlädst, gehen die neueren Episoden verloren.',
    anyway: 'Trotzdem hier bearbeiten',
    load: 'Neuere Version laden',
  },

  fetch: {
    title: 'Von Hugging Face holen',
    sub: 'Hole einen Datensatz auf diesen Roboter, zum Beispiel einen deiner Lehrkraft. Er wird als deine eigene Kopie gespeichert.',
    repoLabel: 'Name auf Hugging Face',
    placeholder: 'z. B. lehrer-mueller/omx_f_wuerfel-demo',
    search: 'Suchen',
    invalid: 'So sieht ein Name auf Hugging Face aus: {pattern}, zum Beispiel {example}.',
    invalidPattern: 'konto/datensatz',
    invalidExample: 'lehrer-mueller/omx_f_wuerfel-demo',
    searching: 'Wird gesucht …',
    otherRobotTitle: 'Für einen anderen Roboter aufgenommen',
    otherRobot: '„{repo}“ stammt von einem anderen Roboter ({robot}). EduBotics kann nur Datensätze vom {ours} öffnen.',
    notFoundTitle: 'Nicht gefunden',
    notFound: 'Den Datensatz gibt es nicht, oder er ist privat und dein Konto darf ihn nicht lesen. Prüfe den Namen.',
    oldFormatTitle: 'Altes Format',
    oldFormat: '„{repo}“ ist in einem älteren Datensatz-Format gespeichert, das EduBotics nicht öffnen kann.',
    unsupportedTitle: 'Unbekanntes Format',
    unsupported: '„{repo}“ ist in einem Format gespeichert, das EduBotics nicht öffnen kann.',
    unreachable: 'Hugging Face ist gerade nicht erreichbar. Versuche es gleich noch einmal.',
    noToken: 'Dein Hugging-Face-Token ist auf dem Roboter nicht aktiv. Prüfe die Karte auf der Startseite.',
    found: 'Gefunden: {repo}',
    visPublic: 'öffentlich',
    visPrivate: 'privat – dein Konto hat Zugriff',
    updated: 'aktualisiert {date}',
    foundLine: '{robot} · {cameras} · {vis} · {updated}',
    camerasPair: '{a}- und {b}-Kamera',
    saveAs: 'Speichern als',
    noName: 'Gib einen Namen ein.',
    nameExists: 'Diesen Namen gibt es hier schon. Wähle einen anderen.',
    savedAs: 'wird gespeichert als {id} · {size}, {free} frei',
    savedAsNoDisk: 'wird gespeichert als {id} · {size}',
    onlineName: 'Diesen Namen gibt es schon auf Hugging Face. Beim Hochladen fragt EduBotics nach.',
    go: 'Holen',
    cancel: 'Abbrechen',
  },

  toast: {
    uploadStarted: '„{name}“ wird hochgeladen …',
    uploadDone: '„{name}“ hochgeladen. Das Training nutzt jetzt diese Version.',
    uploadCancelled: 'Hochladen abgebrochen. Das Training nutzt weiter die bisherige Version auf Hugging Face.',
    downloadStarted: '„{name}“ wird geladen …',
    downloadDone: '„{name}“ ist jetzt auf diesem Roboter.',
    downloadCancelled: 'Laden abgebrochen.',
    partnerUpload: 'Nur {name} kann diesen Datensatz hochladen: Er gehört zum Hugging-Face-Konto von {name}.',
    episodesDeleted: '{count} gelöscht.',
    episodesDeletedUpload: '{count} gelöscht. Lade den Datensatz hoch, damit das Training die neue Version nutzt.',
    uploadAction: 'Jetzt hochladen',
    split: 'Aufgeteilt: „{a}“ hat {na}, „{b}“ {nb}.',
    splitAction: 'Neuen ansehen',
    merged: '„{name}“ ist fertig: {count}. Er liegt nur hier, bis du ihn hochlädst.',
    mergedAction: 'Ansehen',
    datasetDeleted: 'Gelöscht. {size} sind wieder frei.',
    datasetDeletedNoSize: 'Gelöscht.',
  },

  marks: {
    cleared: 'Der Datensatz hat sich geändert. Deine Markierungen wurden entfernt.',
  },

  train: {
    changedWarning: 'Dieser Datensatz wurde hier geändert und noch nicht hochgeladen. Das Training nutzt die ältere Version auf Hugging Face.',
    localWarning: 'Dieser Datensatz liegt nur auf dem Roboter. Lade ihn im Tab Daten hoch, bevor du trainierst.',
    toDaten: 'Zu Daten',
    private: 'Dieser Datensatz ist auf Hugging Face privat. Das Cloud-Training kann private Datensätze noch nicht lesen.',
  },

  hint: {
    stillTitle: 'Arm bewegt sich kaum',
    still: 'Kein Gelenk bewegt sich mehr als {n}°. Vielleicht wurde die Aufgabe nicht ausgeführt.',
    idleEndTitle: 'Lange Pause am Ende',
    idleEnd: '{s} s ohne Bewegung (ab {t}). Das Modell lernt daraus, still zu stehen. Lösche die Episode oder nimm sie neu auf.',
    idleStartTitle: 'Lange Pause am Anfang',
    idleStart: '{s} s ohne Bewegung bis {t}.',
    noGraspTitle: 'Greifer nie geschlossen',
    noGrasp: 'In dieser Episode greift der Arm nichts. War das Absicht?',
    lagTitle: 'Der Follower-Arm kommt nicht hinterher',
    lag: '{joint} liegt bis zu {n}° hinter dem Leader-Arm (bei {t}). Bewege den Leader-Arm ruhiger.',
    shortTitle: 'Viel kürzer als die anderen',
    short: 'Nur {dur} statt meist {median}. Vielleicht wurde zu früh gespeichert.',
    longTitle: 'Viel länger als die anderen',
    long: '{dur} statt meist {median}. Prüfe, ob am Ende noch etwas passiert.',
    seconds: '{s} s',
  },

  camera: {
    gripper: 'Greifer-Kamera',
    scene: 'Szenen-Kamera',
    gripperShort: 'Greifer',
    sceneShort: 'Szenen',
  },

  robots: {
    omx_f: 'OpenMANIPULATOR-X',
    edu6_studio: 'Edu:6',
    edu1_studio: 'Edu:1',
  },

  codecs: {
    h264: 'H.264',
    libx264: 'H.264',
    hevc: 'H.265',
    libx265: 'H.265',
    av1: 'AV1',
    libsvtav1: 'AV1',
    'libaom-av1': 'AV1',
  },

  joints: {
    joint1: 'Gelenk 1 · Basis',
    joint2: 'Gelenk 2 · Schulter',
    joint3: 'Gelenk 3 · Ellbogen',
    joint4: 'Gelenk 4 · Handgelenk',
    joint5: 'Gelenk 5 · Hand drehen',
    gripper_joint_1: 'Greifer',
  },

  dialog: {
    close: 'Schließen',
  },
});

export default DATEN_COPY;
